substitutions:
  device_id: esp2432s024
  build_root: !secret build_root

esphome:
  name: ${device_id}
  build_path: ${build_root}/${device_id}  
  friendly_name: "ESP-2432S024"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG  # Set the logging level to DEBUG
  # baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# SPI bus volgens de veelgebruikte ESP-2432S024 mapping
spi:
  id: spi_bus
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

# Backlight (aan/uit + dimmen)
output:
  - platform: ledc
    id: tft_bl_pwm
    pin: GPIO27
    frequency: 20000 Hz

light:
  - platform: monochromatic
    name: "${friendly_name} Backlight"
    output: tft_bl_pwm
    restore_mode: ALWAYS_ON

font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 16
  - file: "gfonts://Roboto"
    id: font_big
    size: 28

display:
  - platform: mipi_spi
    id: tft
    model: ST7789V
    spi_id: spi_bus

    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO4   # dummy, niet aangesloten
    rotation: 0
    dimensions:
      width: 320
      height: 240

    # percentage van framebuffer
    buffer_size: 25%

    lambda: |-
      it.fill(Color::BLACK);
      it.print(20, 20, id(font_big), Color::WHITE, "ESPHome OK");

touchscreen:
  - platform: xpt2046
    id: touch
    spi_id: spi_bus
    cs_pin: GPIO33
    update_interval: 50ms

    # IRQ pin is niet altijd netjes gedocumenteerd op dit board.
    # Zonder interrupt werkt het ook (polling), alleen iets minder “snappy”.
    # interrupt_pin: GPIOxx

    # Deze moet je vrijwel altijd even kalibreren.
    calibration:
      x_min: 200
      x_max: 3900
      y_min: 200
      y_max: 3900

    on_touch:
      - lambda: |-
          ESP_LOGI("touch", "x=%d y=%d", touch.x, touch.y);
