esphome:
  name: ev-charger
  friendly_name: SmartEVCharger

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG  # Set the logging level to DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_evcharger

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ev-Charger Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

web_server:
    port: 80
    version: 3

# and now we are adding the functionality of this device
# Define the two relays
switch:
  - platform: gpio
    pin: GPIO4 #(NodeMCU pin D2)
    id: charge_on
    name: "Charge On"
    inverted: no  # default the charger is on, active relais to switch off charger
    restore_mode: RESTORE_DEFAULT_ON  # Restore the state after reboot

  - platform: gpio
    pin: GPIO5 # (NodeMCU pin D1)
    id: charge_limit
    name: "Charge 10Amps"
    inverted: yes #default charging is at 16Amps
    restore_mode: RESTORE_DEFAULT_OFF  # Restore the state after reboot

# Add a sensor to monitor WiFi signal strength
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s