# Copyright (c) 2025 Pluimvee
# Configuration Template

# First some basic configuration
#--------------------------------------------
substitutions:
  device_id: kamstrup-wp
  build_root: !secret build_root

esphome:
  name: ${device_id}
  build_path: ${build_root}/${device_id}  
  friendly_name: Multical430 Warmtepomp

esp8266:  
  board: esp12e   # 4MB flash

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

# mDNS expliciet aan laten
mdns:
  disabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  # Sneller verbinden als je alleen 2.4 GHz gebruikt / SSID niet hidden is
  # fast_connect: true
  # power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kamstrup Multical430 Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Enable web server for debugging and control
web_server:
    port: 80
    version: 3

external_components:
  - source: C:/Users/erikv/OneDrive/Archive/Erik/Hobby/ESPHome/components/esphome-kamstrup/components
    components: [ kamstrup ]
    refresh: 1min

# and now we are adding the functionality of this device
#--------------------------------------------
uart:
  - id: uart_kamstrup
    tx_pin: GPIO01
    rx_pin: GPIO03
    baud_rate: 1200
    data_bits: 8
    parity: NONE
    stop_bits: 2
    rx_buffer_size: 512
    debug:

# Sensors die de component publiceert
sensor:
  # Add a sensor to monitor WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    icon: "mdi:wifi"
    update_interval: 60s

  - platform: kamstrup
    uart_id: uart_kamstrup
    update_interval: 10s
    heat_energy:
      name: "Heat Energy"
      icon: "mdi:fire"
    flow:
      name: "Flow"
      icon: "mdi:water-pump"
    power:
      name: "Power"
      icon: "mdi:flash"
      unit_of_measurement: "W"  #convert from kW
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    volume:
      name: "Volume"
      icon: "mdi:water"
    temp1:
      name: "Temperature Out"
      icon: "mdi:thermometer"
    temp2:
      name: "Temperature In"
      icon: "mdi:thermometer"
    temp_diff:
      name: "Delta Temperature"
      icon: "mdi:thermometer-lines"
    custom:
      - name: "Pulse A"
        command: 0x0054
      - name: "Pulse B"
        command: 0x0055