# Copyright (c) 2026 Pluimvee
# ModBus TCP-RTU Bridge ESPHome configuration 

# First some basic configuration
#--------------------------------------------
substitutions:
  device_id: modbus-bridge
  build_root: !secret build_root

packages:
  wifi: !include wifi.yaml
  version: !include version.yaml

esphome:
  name: ${device_id}
  build_path: ${build_root}/${device_id}  
  friendly_name: ModBus Bridge
  project:
    name: 'EcoGrid.ModBus TCP-RTU Bridge'
    version: ${version}

esp8266:
  board: esp12e

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

# Enable logging
logger:
  level: INFO
  baud_rate: 0  # Disable logging on UART (as we need the UART)

#captive_portal:
web_server:
    port: 80
    version: 3

# NOW the device specific logic begins
#--------------------------------------------

# Some special code to allow the ESPHome Modbus TCP-RTU bridge to work
external_components:
  - source: C:/Users/erikv/OneDrive/Archive/Erik/Hobby/ESPHome/components/esphome-modbus-tcp-to-rtu/components
#  - source: github://Pluimvee/esphome-modbus-tcp-to-rtu
    refresh: 1min

# UART configuration for MAX485
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  id: modbus
  rx_buffer_size: 512
#  debug:

modbus_bridge:
   id: bridge
   uart_id: modbus
   port: 502
   buffer_size: 256
   timeout: 3000
   inject_unit_id: 1
   inject_interval: 200

switch:
  - platform: template
    name: "Modbus Injection"
    id: modbus_injection
    icon: "mdi:transmission-tower"
    optimistic: true
    turn_on_action:
      - lambda: "id(bridge).set_modbus_injection(true);"
    turn_off_action:
      - lambda: "id(bridge).set_modbus_injection(false);"

number:
  - platform: template
    name: "Modbus Injection Power"
    id: modbus_injection_power
    icon: "mdi:lightning-bolt"
    unit_of_measurement: W
    min_value: -10000
    max_value: 10000
    step: 1
    optimistic: true
    set_action:
      - lambda: "id(bridge).set_inject_power(x);"

#and some sensors to monitor the bridge itself
binary_sensor:
  - platform: modbus_bridge
    connected:
      name: Connected
      icon: "mdi:connection"

sensor:
  - platform: modbus_bridge
    connection_count:
      name: "Number of connections"
      icon: "mdi:lan-connect"

  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
    icon: "mdi:wifi"
