# Copyright (c) 2026 Pluimvee
# Omnik Inverter WiFi Bridge

# First some basic configuration
#--------------------------------------------
substitutions:
  device_id: omnik-bridge
  build_root: !secret build_root
  # 19.03 MWh uit Solarman met ingangsdatum 10 dec 2012 en laatste update 8 nov 2023
  # + geschatte missende periode dec 2023 t/m 11 feb 2026 obv HA statistieken (dmv codex)
  min_total_kwh: "22790.0"

esphome:
  name: ${device_id}
  friendly_name: Omnik Inverter
  build_path: ${build_root}/${device_id}  
  project:
    name: 'EcoGrid.Omnik Inverter WiFi Bridge'
    version: Feb 10 2026
  on_boot:
    priority: -100
    then:
      - lambda: |-
          const float min_total = ${min_total_kwh};
          if (id(energy_total) < min_total) {
            id(energy_total) = min_total;
          }
          id(energy_total_sensor).publish_state(id(energy_total));

esp8266:
  board: esp01_1m
  restore_from_flash: true

preferences:
  flash_write_interval: 15min

logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  max_connections: 6
  listen_backlog: 2

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  # Sneller verbinden als je alleen 2.4 GHz gebruikt / SSID niet hidden is
  fast_connect: true
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Outside Climate Hotspot"
    password: !secret wifi_ap_password

## Disable captive portal temporarily to reduce AP/DNS overhead
# captive_portal:

# Enable web server for debugging and control
web_server:
    port: 80
    version: 3

# -- Time Setup --
time:
  - platform: homeassistant
    id: time_id

# Persistente teller voor inverter-total (inverter reset 's nachts)
globals:
  - id: energy_total
    type: float
    restore_value: true
    initial_value: ${min_total_kwh}
  - id: energy_last_raw
    type: float
    restore_value: true
    initial_value: '-1.0'

# and now we are adding the functionality of this device
#--------------------------------------------
external_components:
  - source: C:/Users/erikv/OneDrive/Archive/Erik/Hobby/ESPHome/components/esphome-omnik/components
    components: [omnik_bridge]
    refresh: 1min

omnik_bridge:
  ap_ssid: "OmnikPortal"
  ap_password: "OmnikKey"
  ap_ip: "176.58.117.69"
  ap_subnet: "255.255.255.0"
  port: 10004
  channel: 0
  temperature:
    name: "Temperature"
    icon: "mdi:thermometer"
  power:
    name: "Power"
    icon: "mdi:flash"
  ac_frequency:
    name: "AC Frequency"
    icon: "mdi:sine-wave"
  ac_voltage:
    name: "AC Voltage"
    icon: "mdi:current-ac"
  energy_today:
    name: "Energy Today"
    icon: "mdi:calendar-today"
    id: omnik_energy_today
    on_value:
      then:
        - lambda: |-
            float current = id(omnik_energy_today).state;
            if (!isfinite(current) || current < 0.0f) {
              return;
            }
            // Eerste geldige sample na flash restore: alleen baseline zetten.
            if (id(energy_last_raw) < 0.0f) {
              id(energy_last_raw) = current;
              id(energy_total_sensor).publish_state(id(energy_total));
              return;
            }

            float delta = 0.0f;
            if (current >= id(energy_last_raw)) {
              // Normale situatie binnen dezelfde dag.
              delta = current - id(energy_last_raw);
            } else {
              // Bron heeft daggeheugen en is gereset (meestal rond middernacht).
              delta = current;
            }
            // Sanity guard tegen corrupte sprongen.
            if (delta > 0.0f && delta < 25.0f) {
              id(energy_total) += delta;
            }
            const float min_total = ${min_total_kwh};
            if (id(energy_total) < min_total) {
              id(energy_total) = min_total;
            }
            id(energy_last_raw) = current;
            id(energy_total_sensor).publish_state(id(energy_total));

  operating_hours:
    name: "Operating Hours"
    icon: "mdi:progress-clock"
  voltage_pv1:
    name: "PV Voltage"
    icon: "mdi:solar-power"
  current_pv1:
    name: "PV Current"
    icon: "mdi:current-dc"
  current_ac1:
    name: "AC Current"
    icon: "mdi:current-ac"
  connected:
    name: "Connected"
    icon: "mdi:connection"
  logger_id:
    name: "Logger ID"
    icon: "mdi:identifier"
  inverter_id:
    name: "Inverter ID"
    icon: "mdi:identifier"

sensor:
  - platform: wifi_signal
    name: "Signal Strength"
    icon: "mdi:wifi"
    update_interval: 10s

  - platform: template
    id: energy_total_sensor
    name: "Energy"
    icon: "mdi:counter"
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    lambda: |-
      return id(energy_total);

interval:
  # -- Midnight reset for "Energy Used Today and Operating Hours" --
  - interval: 60s
    then:
      - lambda: |-
          static int last_day = -1;
          auto time = id(time_id).now();
          if (time.is_valid()) {
            // initialize last_day after boot
            if (last_day == -1) {
              last_day = time.day_of_year;
            }
            // Reset omnik_energy_today at midnight
            if (time.day_of_year != last_day) {
              last_day = time.day_of_year;
              id(omnik_energy_today).publish_state(0.0f);
            }
          }
