esphome:
  name: outsidetemp
  friendly_name: Outside Temperature

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: INFO
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
#    password: !secret ota_password
    password: "52ade08de3deb7dd0cf675a40c60c1bb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Outsidetemp Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

web_server:
    port: 80
    version: 3

# and now we are adding the functionality of this device
one_wire:
  - platform: gpio
    pin: GPIO05

sensor:
  # Add a sensor to monitor WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
  - platform: dallas_temp
    address: 0xdb3c900457e5f828
    name: "Outside Temperature"
