# Copyright (c) 2025 Pluimvee
# Resideo ESPHome configuration - Woonkamer

substitutions:
  device_id: resideo-woonkamer
  build_root: !secret build_root
  friendly_name: Resideo Woonkamer
  temp_offset: '-5.0'
  humidity_offset: '-3.5'

packages:
  base: !include resideo-base.yaml
