# Copyright (c) 2025 Pluimvee
# Resideo ESPHome configuration - Slaapkamer Yara

substitutions:
  device_id: resideo-yara
  build_root: !secret build_root
  friendly_name: Resideo Slaapkamer Yara
  temp_offset: '-5.7'
  humidity_offset: '2.3'

packages:
  base: !include resideo-base.yaml
