# Copyright (c) 2025 Pluimvee
# Resideo ESPHome configuration 

# First some basic configuration
#--------------------------------------------
esphome:
  name: resideo-zolder
  friendly_name: Resideo Zolder

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Resideo"
    password: !secret wifi_ap_password

captive_portal:

# Enable web server for debugging and control
web_server:
    port: 80
    version: 3

# Enable logging
logger:
  level: INFO  
  baud_rate: 0  # Disable logging on UART (as we need the UART)

# NOW the device specific logic begins
#--------------------------------------------

# Some special code to allow the Resideo mod to work
external_components:
  # - source: github://Pluimvee/esphome-resideo
  - source: C:\Users\erikv\OneDrive\Archive\Erik\Hobby\ESPHome/components/esphome-resideo/components
    refresh: 1min
    components: [cht8305_sniffer, cm1106_sniffer]

sensor:
  # Add a sensor to monitor WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
    icon: "mdi:wifi"

  - platform: cht8305_sniffer
    temperature:
      name: "Temperature"
      filters:
        - calibrate_linear:
          - 0.00 -> 0.00
          - 28.0 -> 22.0
    humidity:
      name: "Humidity"
      filters:
        - offset: 0.1  # Adjust humidity offset if needed

  - platform: cm1106_sniffer
    name: "Carbon-dioxide"

