# Copyright (c) 2025 Pluimvee
# Resideo ESPHome configuration 

# First some basic configuration
#--------------------------------------------
substitutions:
  device_id: resideo-yara
  build_root: !secret build_root

esphome:
  name: ${device_id}
  build_path: ${build_root}/${device_id}  
  friendly_name: Resideo Slaapkamer Yara
  project:
    name: 'EcoGrid.Climate Monitor (Resideo mod)'
    version: Jan 12 2026

esp8266:
  board: esp01_1m
  restore_from_flash: false

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Resideo Yara"
    password: !secret wifi_ap_password

captive_portal:

# Enable web server for debugging and control
web_server:
    port: 80
    version: 3

# Enable logging
logger:
  level: INFO  
  baud_rate: 0  # Disable logging on UART (as we need the UART)

# NOW the device specific logic begins
#--------------------------------------------

# Some special code to allow the Resideo mod to work
external_components:
  - source: github://Pluimvee/esphome-resideo
    refresh: 5min
    components: [cht8305_sniffer, cm1106_sniffer]

sensor:
  # Add a sensor to monitor WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
    icon: "mdi:wifi"

  - platform: cht8305_sniffer
    temperature:
      name: "Temperature"
      filters:
        - offset: -5.7
        - lambda: |-
            if (x < 0.0f || x > 40.0f) return NAN;
            return x;
        - filter_out: nan
    humidity:
      name: "Humidity"
      filters:
        - offset: 2.3  # Adjust humidity offset if needed

  - platform: cm1106_sniffer
    name: "Carbon-dioxide"
