# Copyright (c) 2025 Pluimvee
# Monitor the floor heating Ta and Tr of the living room, kitchen and dining room

# First some basic configuration
#--------------------------------------------
substitutions:
  device_id: floor-temp
  build_root: !secret build_root

packages:
  wifi: !include wifi.yaml
  version: !include version.yaml

esphome:
  name: ${device_id}
  build_path: ${build_root}/${device_id}  
  friendly_name: Floor Temperature
  project:
    name: 'EcoGrid.Floor Temperature Monitor'
    version: ${version}

esp8266:
  board: esp12e

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

# Enable logging
logger:
  level: INFO  # Set the logging level to DEBUG
  baud_rate: 0

debug:
  update_interval: never

# Enable web server for debugging and control
web_server:
    port: 80
    version: 3

# NOW the device specific logic begins
#--------------------------------------------
one_wire:
  - platform: gpio
    pin: GPIO05
    
switch:
  - platform: gpio
    pin:
      number: GPIO2
      mode: output
    id: led
    
sensor:
  # Add a sensor to monitor WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
    icon: "mdi:wifi"

  # Ta recieved from Source
  - platform: dallas_temp
    address: 0xd23cd40457914c28
    name: Ta Verdeler (Red)
    icon: mdi:heating-coil
    update_interval: 5s
    on_value:
      then:
        - switch.toggle: led

  # Tr sensors for the different rooms
  - platform: dallas_temp
    address: 0x323c34045709be28
    name: Tr Eetkamer (White)
    icon: mdi:thermometer-chevron-up
    update_interval: 5s

  - platform: dallas_temp
    address: 0x963cdf04572d8528
    name: Tr Keuken (Blue)
    icon: mdi:thermometer-chevron-up
    update_interval: 5s

  - platform: dallas_temp
    address: 0xa43c130457bc1528
    name: Tr Woonkamer (Yellow)
    icon: mdi:thermometer-chevron-up
    update_interval: 5s
   
  # - platform: template
  #   name: "Flash chip size"
  #   unit_of_measurement: "kB"
  #   lambda: |-
  #     return ESP.getFlashChipRealSize() / 1024.0;
  #   update_interval: 60s